// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lars.proto

#ifndef PROTOBUF_lars_2eproto__INCLUDED
#define PROTOBUF_lars_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace lars {
class GetHostRequest;
class GetHostRequestDefaultTypeInternal;
extern GetHostRequestDefaultTypeInternal _GetHostRequest_default_instance_;
class GetHostResponse;
class GetHostResponseDefaultTypeInternal;
extern GetHostResponseDefaultTypeInternal _GetHostResponse_default_instance_;
class GetRouteRequest;
class GetRouteRequestDefaultTypeInternal;
extern GetRouteRequestDefaultTypeInternal _GetRouteRequest_default_instance_;
class GetRouteResponse;
class GetRouteResponseDefaultTypeInternal;
extern GetRouteResponseDefaultTypeInternal _GetRouteResponse_default_instance_;
class HostCallResult;
class HostCallResultDefaultTypeInternal;
extern HostCallResultDefaultTypeInternal _HostCallResult_default_instance_;
class HostInfo;
class HostInfoDefaultTypeInternal;
extern HostInfoDefaultTypeInternal _HostInfo_default_instance_;
class ReportRequest;
class ReportRequestDefaultTypeInternal;
extern ReportRequestDefaultTypeInternal _ReportRequest_default_instance_;
class ReportStatusRequest;
class ReportStatusRequestDefaultTypeInternal;
extern ReportStatusRequestDefaultTypeInternal _ReportStatusRequest_default_instance_;
}  // namespace lars

namespace lars {

namespace protobuf_lars_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_lars_2eproto

enum MessageId {
  ID_UNKONW = 0,
  ID_GetRouteRequest = 1,
  ID_GetRouteResponse = 2,
  ID_ReportStatusRequest = 3,
  ID_GetHostRequest = 4,
  ID_GetHostResponse = 5,
  ID_ReportRequest = 6,
  ID_API_GetRouteRequest = 7,
  ID_API_GetRouteResponse = 8,
  MessageId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  MessageId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool MessageId_IsValid(int value);
const MessageId MessageId_MIN = ID_UNKONW;
const MessageId MessageId_MAX = ID_API_GetRouteResponse;
const int MessageId_ARRAYSIZE = MessageId_MAX + 1;

const ::google::protobuf::EnumDescriptor* MessageId_descriptor();
inline const ::std::string& MessageId_Name(MessageId value) {
  return ::google::protobuf::internal::NameOfEnum(
    MessageId_descriptor(), value);
}
inline bool MessageId_Parse(
    const ::std::string& name, MessageId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MessageId>(
    MessageId_descriptor(), name, value);
}
enum LarsRetCode {
  RET_SUCC = 0,
  RET_OVERLOAD = 1,
  RET_SYSTEM_ERROR = 2,
  RET_NOEXIST = 3,
  LarsRetCode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  LarsRetCode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool LarsRetCode_IsValid(int value);
const LarsRetCode LarsRetCode_MIN = RET_SUCC;
const LarsRetCode LarsRetCode_MAX = RET_NOEXIST;
const int LarsRetCode_ARRAYSIZE = LarsRetCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* LarsRetCode_descriptor();
inline const ::std::string& LarsRetCode_Name(LarsRetCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    LarsRetCode_descriptor(), value);
}
inline bool LarsRetCode_Parse(
    const ::std::string& name, LarsRetCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<LarsRetCode>(
    LarsRetCode_descriptor(), name, value);
}
// ===================================================================

class HostInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lars.HostInfo) */ {
 public:
  HostInfo();
  virtual ~HostInfo();

  HostInfo(const HostInfo& from);

  inline HostInfo& operator=(const HostInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  HostInfo(HostInfo&& from) noexcept
    : HostInfo() {
    *this = ::std::move(from);
  }

  inline HostInfo& operator=(HostInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const HostInfo& default_instance();

  static inline const HostInfo* internal_default_instance() {
    return reinterpret_cast<const HostInfo*>(
               &_HostInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(HostInfo* other);
  friend void swap(HostInfo& a, HostInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline HostInfo* New() const PROTOBUF_FINAL { return New(NULL); }

  HostInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const HostInfo& from);
  void MergeFrom(const HostInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(HostInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 ip = 1;
  void clear_ip();
  static const int kIpFieldNumber = 1;
  ::google::protobuf::int32 ip() const;
  void set_ip(::google::protobuf::int32 value);

  // int32 port = 2;
  void clear_port();
  static const int kPortFieldNumber = 2;
  ::google::protobuf::int32 port() const;
  void set_port(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:lars.HostInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 ip_;
  ::google::protobuf::int32 port_;
  mutable int _cached_size_;
  friend struct protobuf_lars_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetRouteRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lars.GetRouteRequest) */ {
 public:
  GetRouteRequest();
  virtual ~GetRouteRequest();

  GetRouteRequest(const GetRouteRequest& from);

  inline GetRouteRequest& operator=(const GetRouteRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetRouteRequest(GetRouteRequest&& from) noexcept
    : GetRouteRequest() {
    *this = ::std::move(from);
  }

  inline GetRouteRequest& operator=(GetRouteRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetRouteRequest& default_instance();

  static inline const GetRouteRequest* internal_default_instance() {
    return reinterpret_cast<const GetRouteRequest*>(
               &_GetRouteRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(GetRouteRequest* other);
  friend void swap(GetRouteRequest& a, GetRouteRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetRouteRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  GetRouteRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetRouteRequest& from);
  void MergeFrom(const GetRouteRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetRouteRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 modid = 1;
  void clear_modid();
  static const int kModidFieldNumber = 1;
  ::google::protobuf::int32 modid() const;
  void set_modid(::google::protobuf::int32 value);

  // int32 cmdid = 2;
  void clear_cmdid();
  static const int kCmdidFieldNumber = 2;
  ::google::protobuf::int32 cmdid() const;
  void set_cmdid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:lars.GetRouteRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 modid_;
  ::google::protobuf::int32 cmdid_;
  mutable int _cached_size_;
  friend struct protobuf_lars_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetRouteResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lars.GetRouteResponse) */ {
 public:
  GetRouteResponse();
  virtual ~GetRouteResponse();

  GetRouteResponse(const GetRouteResponse& from);

  inline GetRouteResponse& operator=(const GetRouteResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetRouteResponse(GetRouteResponse&& from) noexcept
    : GetRouteResponse() {
    *this = ::std::move(from);
  }

  inline GetRouteResponse& operator=(GetRouteResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetRouteResponse& default_instance();

  static inline const GetRouteResponse* internal_default_instance() {
    return reinterpret_cast<const GetRouteResponse*>(
               &_GetRouteResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(GetRouteResponse* other);
  friend void swap(GetRouteResponse& a, GetRouteResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetRouteResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  GetRouteResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetRouteResponse& from);
  void MergeFrom(const GetRouteResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetRouteResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .lars.HostInfo host = 3;
  int host_size() const;
  void clear_host();
  static const int kHostFieldNumber = 3;
  const ::lars::HostInfo& host(int index) const;
  ::lars::HostInfo* mutable_host(int index);
  ::lars::HostInfo* add_host();
  ::google::protobuf::RepeatedPtrField< ::lars::HostInfo >*
      mutable_host();
  const ::google::protobuf::RepeatedPtrField< ::lars::HostInfo >&
      host() const;

  // int32 modid = 1;
  void clear_modid();
  static const int kModidFieldNumber = 1;
  ::google::protobuf::int32 modid() const;
  void set_modid(::google::protobuf::int32 value);

  // int32 cmdid = 2;
  void clear_cmdid();
  static const int kCmdidFieldNumber = 2;
  ::google::protobuf::int32 cmdid() const;
  void set_cmdid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:lars.GetRouteResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::lars::HostInfo > host_;
  ::google::protobuf::int32 modid_;
  ::google::protobuf::int32 cmdid_;
  mutable int _cached_size_;
  friend struct protobuf_lars_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class HostCallResult : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lars.HostCallResult) */ {
 public:
  HostCallResult();
  virtual ~HostCallResult();

  HostCallResult(const HostCallResult& from);

  inline HostCallResult& operator=(const HostCallResult& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  HostCallResult(HostCallResult&& from) noexcept
    : HostCallResult() {
    *this = ::std::move(from);
  }

  inline HostCallResult& operator=(HostCallResult&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const HostCallResult& default_instance();

  static inline const HostCallResult* internal_default_instance() {
    return reinterpret_cast<const HostCallResult*>(
               &_HostCallResult_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(HostCallResult* other);
  friend void swap(HostCallResult& a, HostCallResult& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline HostCallResult* New() const PROTOBUF_FINAL { return New(NULL); }

  HostCallResult* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const HostCallResult& from);
  void MergeFrom(const HostCallResult& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(HostCallResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 ip = 1;
  void clear_ip();
  static const int kIpFieldNumber = 1;
  ::google::protobuf::int32 ip() const;
  void set_ip(::google::protobuf::int32 value);

  // int32 port = 2;
  void clear_port();
  static const int kPortFieldNumber = 2;
  ::google::protobuf::int32 port() const;
  void set_port(::google::protobuf::int32 value);

  // uint32 succ = 3;
  void clear_succ();
  static const int kSuccFieldNumber = 3;
  ::google::protobuf::uint32 succ() const;
  void set_succ(::google::protobuf::uint32 value);

  // uint32 err = 4;
  void clear_err();
  static const int kErrFieldNumber = 4;
  ::google::protobuf::uint32 err() const;
  void set_err(::google::protobuf::uint32 value);

  // bool overload = 5;
  void clear_overload();
  static const int kOverloadFieldNumber = 5;
  bool overload() const;
  void set_overload(bool value);

  // @@protoc_insertion_point(class_scope:lars.HostCallResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 ip_;
  ::google::protobuf::int32 port_;
  ::google::protobuf::uint32 succ_;
  ::google::protobuf::uint32 err_;
  bool overload_;
  mutable int _cached_size_;
  friend struct protobuf_lars_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReportStatusRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lars.ReportStatusRequest) */ {
 public:
  ReportStatusRequest();
  virtual ~ReportStatusRequest();

  ReportStatusRequest(const ReportStatusRequest& from);

  inline ReportStatusRequest& operator=(const ReportStatusRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReportStatusRequest(ReportStatusRequest&& from) noexcept
    : ReportStatusRequest() {
    *this = ::std::move(from);
  }

  inline ReportStatusRequest& operator=(ReportStatusRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReportStatusRequest& default_instance();

  static inline const ReportStatusRequest* internal_default_instance() {
    return reinterpret_cast<const ReportStatusRequest*>(
               &_ReportStatusRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(ReportStatusRequest* other);
  friend void swap(ReportStatusRequest& a, ReportStatusRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReportStatusRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  ReportStatusRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ReportStatusRequest& from);
  void MergeFrom(const ReportStatusRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ReportStatusRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .lars.HostCallResult results = 4;
  int results_size() const;
  void clear_results();
  static const int kResultsFieldNumber = 4;
  const ::lars::HostCallResult& results(int index) const;
  ::lars::HostCallResult* mutable_results(int index);
  ::lars::HostCallResult* add_results();
  ::google::protobuf::RepeatedPtrField< ::lars::HostCallResult >*
      mutable_results();
  const ::google::protobuf::RepeatedPtrField< ::lars::HostCallResult >&
      results() const;

  // int32 modid = 1;
  void clear_modid();
  static const int kModidFieldNumber = 1;
  ::google::protobuf::int32 modid() const;
  void set_modid(::google::protobuf::int32 value);

  // int32 cmdid = 2;
  void clear_cmdid();
  static const int kCmdidFieldNumber = 2;
  ::google::protobuf::int32 cmdid() const;
  void set_cmdid(::google::protobuf::int32 value);

  // int32 caller = 3;
  void clear_caller();
  static const int kCallerFieldNumber = 3;
  ::google::protobuf::int32 caller() const;
  void set_caller(::google::protobuf::int32 value);

  // uint32 ts = 5;
  void clear_ts();
  static const int kTsFieldNumber = 5;
  ::google::protobuf::uint32 ts() const;
  void set_ts(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:lars.ReportStatusRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::lars::HostCallResult > results_;
  ::google::protobuf::int32 modid_;
  ::google::protobuf::int32 cmdid_;
  ::google::protobuf::int32 caller_;
  ::google::protobuf::uint32 ts_;
  mutable int _cached_size_;
  friend struct protobuf_lars_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetHostRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lars.GetHostRequest) */ {
 public:
  GetHostRequest();
  virtual ~GetHostRequest();

  GetHostRequest(const GetHostRequest& from);

  inline GetHostRequest& operator=(const GetHostRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetHostRequest(GetHostRequest&& from) noexcept
    : GetHostRequest() {
    *this = ::std::move(from);
  }

  inline GetHostRequest& operator=(GetHostRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetHostRequest& default_instance();

  static inline const GetHostRequest* internal_default_instance() {
    return reinterpret_cast<const GetHostRequest*>(
               &_GetHostRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(GetHostRequest* other);
  friend void swap(GetHostRequest& a, GetHostRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetHostRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  GetHostRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetHostRequest& from);
  void MergeFrom(const GetHostRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetHostRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 seq = 1;
  void clear_seq();
  static const int kSeqFieldNumber = 1;
  ::google::protobuf::uint32 seq() const;
  void set_seq(::google::protobuf::uint32 value);

  // int32 modid = 2;
  void clear_modid();
  static const int kModidFieldNumber = 2;
  ::google::protobuf::int32 modid() const;
  void set_modid(::google::protobuf::int32 value);

  // int32 cmdid = 3;
  void clear_cmdid();
  static const int kCmdidFieldNumber = 3;
  ::google::protobuf::int32 cmdid() const;
  void set_cmdid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:lars.GetHostRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 seq_;
  ::google::protobuf::int32 modid_;
  ::google::protobuf::int32 cmdid_;
  mutable int _cached_size_;
  friend struct protobuf_lars_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetHostResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lars.GetHostResponse) */ {
 public:
  GetHostResponse();
  virtual ~GetHostResponse();

  GetHostResponse(const GetHostResponse& from);

  inline GetHostResponse& operator=(const GetHostResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetHostResponse(GetHostResponse&& from) noexcept
    : GetHostResponse() {
    *this = ::std::move(from);
  }

  inline GetHostResponse& operator=(GetHostResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetHostResponse& default_instance();

  static inline const GetHostResponse* internal_default_instance() {
    return reinterpret_cast<const GetHostResponse*>(
               &_GetHostResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(GetHostResponse* other);
  friend void swap(GetHostResponse& a, GetHostResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetHostResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  GetHostResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetHostResponse& from);
  void MergeFrom(const GetHostResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetHostResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .lars.HostInfo host = 5;
  bool has_host() const;
  void clear_host();
  static const int kHostFieldNumber = 5;
  const ::lars::HostInfo& host() const;
  ::lars::HostInfo* mutable_host();
  ::lars::HostInfo* release_host();
  void set_allocated_host(::lars::HostInfo* host);

  // uint32 seq = 1;
  void clear_seq();
  static const int kSeqFieldNumber = 1;
  ::google::protobuf::uint32 seq() const;
  void set_seq(::google::protobuf::uint32 value);

  // int32 modid = 2;
  void clear_modid();
  static const int kModidFieldNumber = 2;
  ::google::protobuf::int32 modid() const;
  void set_modid(::google::protobuf::int32 value);

  // int32 cmdid = 3;
  void clear_cmdid();
  static const int kCmdidFieldNumber = 3;
  ::google::protobuf::int32 cmdid() const;
  void set_cmdid(::google::protobuf::int32 value);

  // int32 retcode = 4;
  void clear_retcode();
  static const int kRetcodeFieldNumber = 4;
  ::google::protobuf::int32 retcode() const;
  void set_retcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:lars.GetHostResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::lars::HostInfo* host_;
  ::google::protobuf::uint32 seq_;
  ::google::protobuf::int32 modid_;
  ::google::protobuf::int32 cmdid_;
  ::google::protobuf::int32 retcode_;
  mutable int _cached_size_;
  friend struct protobuf_lars_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReportRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lars.ReportRequest) */ {
 public:
  ReportRequest();
  virtual ~ReportRequest();

  ReportRequest(const ReportRequest& from);

  inline ReportRequest& operator=(const ReportRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReportRequest(ReportRequest&& from) noexcept
    : ReportRequest() {
    *this = ::std::move(from);
  }

  inline ReportRequest& operator=(ReportRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReportRequest& default_instance();

  static inline const ReportRequest* internal_default_instance() {
    return reinterpret_cast<const ReportRequest*>(
               &_ReportRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(ReportRequest* other);
  friend void swap(ReportRequest& a, ReportRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReportRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  ReportRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ReportRequest& from);
  void MergeFrom(const ReportRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ReportRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .lars.HostInfo host = 3;
  bool has_host() const;
  void clear_host();
  static const int kHostFieldNumber = 3;
  const ::lars::HostInfo& host() const;
  ::lars::HostInfo* mutable_host();
  ::lars::HostInfo* release_host();
  void set_allocated_host(::lars::HostInfo* host);

  // int32 modid = 1;
  void clear_modid();
  static const int kModidFieldNumber = 1;
  ::google::protobuf::int32 modid() const;
  void set_modid(::google::protobuf::int32 value);

  // int32 cmdid = 2;
  void clear_cmdid();
  static const int kCmdidFieldNumber = 2;
  ::google::protobuf::int32 cmdid() const;
  void set_cmdid(::google::protobuf::int32 value);

  // int32 retcode = 4;
  void clear_retcode();
  static const int kRetcodeFieldNumber = 4;
  ::google::protobuf::int32 retcode() const;
  void set_retcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:lars.ReportRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::lars::HostInfo* host_;
  ::google::protobuf::int32 modid_;
  ::google::protobuf::int32 cmdid_;
  ::google::protobuf::int32 retcode_;
  mutable int _cached_size_;
  friend struct protobuf_lars_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HostInfo

// int32 ip = 1;
inline void HostInfo::clear_ip() {
  ip_ = 0;
}
inline ::google::protobuf::int32 HostInfo::ip() const {
  // @@protoc_insertion_point(field_get:lars.HostInfo.ip)
  return ip_;
}
inline void HostInfo::set_ip(::google::protobuf::int32 value) {
  
  ip_ = value;
  // @@protoc_insertion_point(field_set:lars.HostInfo.ip)
}

// int32 port = 2;
inline void HostInfo::clear_port() {
  port_ = 0;
}
inline ::google::protobuf::int32 HostInfo::port() const {
  // @@protoc_insertion_point(field_get:lars.HostInfo.port)
  return port_;
}
inline void HostInfo::set_port(::google::protobuf::int32 value) {
  
  port_ = value;
  // @@protoc_insertion_point(field_set:lars.HostInfo.port)
}

// -------------------------------------------------------------------

// GetRouteRequest

// int32 modid = 1;
inline void GetRouteRequest::clear_modid() {
  modid_ = 0;
}
inline ::google::protobuf::int32 GetRouteRequest::modid() const {
  // @@protoc_insertion_point(field_get:lars.GetRouteRequest.modid)
  return modid_;
}
inline void GetRouteRequest::set_modid(::google::protobuf::int32 value) {
  
  modid_ = value;
  // @@protoc_insertion_point(field_set:lars.GetRouteRequest.modid)
}

// int32 cmdid = 2;
inline void GetRouteRequest::clear_cmdid() {
  cmdid_ = 0;
}
inline ::google::protobuf::int32 GetRouteRequest::cmdid() const {
  // @@protoc_insertion_point(field_get:lars.GetRouteRequest.cmdid)
  return cmdid_;
}
inline void GetRouteRequest::set_cmdid(::google::protobuf::int32 value) {
  
  cmdid_ = value;
  // @@protoc_insertion_point(field_set:lars.GetRouteRequest.cmdid)
}

// -------------------------------------------------------------------

// GetRouteResponse

// int32 modid = 1;
inline void GetRouteResponse::clear_modid() {
  modid_ = 0;
}
inline ::google::protobuf::int32 GetRouteResponse::modid() const {
  // @@protoc_insertion_point(field_get:lars.GetRouteResponse.modid)
  return modid_;
}
inline void GetRouteResponse::set_modid(::google::protobuf::int32 value) {
  
  modid_ = value;
  // @@protoc_insertion_point(field_set:lars.GetRouteResponse.modid)
}

// int32 cmdid = 2;
inline void GetRouteResponse::clear_cmdid() {
  cmdid_ = 0;
}
inline ::google::protobuf::int32 GetRouteResponse::cmdid() const {
  // @@protoc_insertion_point(field_get:lars.GetRouteResponse.cmdid)
  return cmdid_;
}
inline void GetRouteResponse::set_cmdid(::google::protobuf::int32 value) {
  
  cmdid_ = value;
  // @@protoc_insertion_point(field_set:lars.GetRouteResponse.cmdid)
}

// repeated .lars.HostInfo host = 3;
inline int GetRouteResponse::host_size() const {
  return host_.size();
}
inline void GetRouteResponse::clear_host() {
  host_.Clear();
}
inline const ::lars::HostInfo& GetRouteResponse::host(int index) const {
  // @@protoc_insertion_point(field_get:lars.GetRouteResponse.host)
  return host_.Get(index);
}
inline ::lars::HostInfo* GetRouteResponse::mutable_host(int index) {
  // @@protoc_insertion_point(field_mutable:lars.GetRouteResponse.host)
  return host_.Mutable(index);
}
inline ::lars::HostInfo* GetRouteResponse::add_host() {
  // @@protoc_insertion_point(field_add:lars.GetRouteResponse.host)
  return host_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::lars::HostInfo >*
GetRouteResponse::mutable_host() {
  // @@protoc_insertion_point(field_mutable_list:lars.GetRouteResponse.host)
  return &host_;
}
inline const ::google::protobuf::RepeatedPtrField< ::lars::HostInfo >&
GetRouteResponse::host() const {
  // @@protoc_insertion_point(field_list:lars.GetRouteResponse.host)
  return host_;
}

// -------------------------------------------------------------------

// HostCallResult

// int32 ip = 1;
inline void HostCallResult::clear_ip() {
  ip_ = 0;
}
inline ::google::protobuf::int32 HostCallResult::ip() const {
  // @@protoc_insertion_point(field_get:lars.HostCallResult.ip)
  return ip_;
}
inline void HostCallResult::set_ip(::google::protobuf::int32 value) {
  
  ip_ = value;
  // @@protoc_insertion_point(field_set:lars.HostCallResult.ip)
}

// int32 port = 2;
inline void HostCallResult::clear_port() {
  port_ = 0;
}
inline ::google::protobuf::int32 HostCallResult::port() const {
  // @@protoc_insertion_point(field_get:lars.HostCallResult.port)
  return port_;
}
inline void HostCallResult::set_port(::google::protobuf::int32 value) {
  
  port_ = value;
  // @@protoc_insertion_point(field_set:lars.HostCallResult.port)
}

// uint32 succ = 3;
inline void HostCallResult::clear_succ() {
  succ_ = 0u;
}
inline ::google::protobuf::uint32 HostCallResult::succ() const {
  // @@protoc_insertion_point(field_get:lars.HostCallResult.succ)
  return succ_;
}
inline void HostCallResult::set_succ(::google::protobuf::uint32 value) {
  
  succ_ = value;
  // @@protoc_insertion_point(field_set:lars.HostCallResult.succ)
}

// uint32 err = 4;
inline void HostCallResult::clear_err() {
  err_ = 0u;
}
inline ::google::protobuf::uint32 HostCallResult::err() const {
  // @@protoc_insertion_point(field_get:lars.HostCallResult.err)
  return err_;
}
inline void HostCallResult::set_err(::google::protobuf::uint32 value) {
  
  err_ = value;
  // @@protoc_insertion_point(field_set:lars.HostCallResult.err)
}

// bool overload = 5;
inline void HostCallResult::clear_overload() {
  overload_ = false;
}
inline bool HostCallResult::overload() const {
  // @@protoc_insertion_point(field_get:lars.HostCallResult.overload)
  return overload_;
}
inline void HostCallResult::set_overload(bool value) {
  
  overload_ = value;
  // @@protoc_insertion_point(field_set:lars.HostCallResult.overload)
}

// -------------------------------------------------------------------

// ReportStatusRequest

// int32 modid = 1;
inline void ReportStatusRequest::clear_modid() {
  modid_ = 0;
}
inline ::google::protobuf::int32 ReportStatusRequest::modid() const {
  // @@protoc_insertion_point(field_get:lars.ReportStatusRequest.modid)
  return modid_;
}
inline void ReportStatusRequest::set_modid(::google::protobuf::int32 value) {
  
  modid_ = value;
  // @@protoc_insertion_point(field_set:lars.ReportStatusRequest.modid)
}

// int32 cmdid = 2;
inline void ReportStatusRequest::clear_cmdid() {
  cmdid_ = 0;
}
inline ::google::protobuf::int32 ReportStatusRequest::cmdid() const {
  // @@protoc_insertion_point(field_get:lars.ReportStatusRequest.cmdid)
  return cmdid_;
}
inline void ReportStatusRequest::set_cmdid(::google::protobuf::int32 value) {
  
  cmdid_ = value;
  // @@protoc_insertion_point(field_set:lars.ReportStatusRequest.cmdid)
}

// int32 caller = 3;
inline void ReportStatusRequest::clear_caller() {
  caller_ = 0;
}
inline ::google::protobuf::int32 ReportStatusRequest::caller() const {
  // @@protoc_insertion_point(field_get:lars.ReportStatusRequest.caller)
  return caller_;
}
inline void ReportStatusRequest::set_caller(::google::protobuf::int32 value) {
  
  caller_ = value;
  // @@protoc_insertion_point(field_set:lars.ReportStatusRequest.caller)
}

// repeated .lars.HostCallResult results = 4;
inline int ReportStatusRequest::results_size() const {
  return results_.size();
}
inline void ReportStatusRequest::clear_results() {
  results_.Clear();
}
inline const ::lars::HostCallResult& ReportStatusRequest::results(int index) const {
  // @@protoc_insertion_point(field_get:lars.ReportStatusRequest.results)
  return results_.Get(index);
}
inline ::lars::HostCallResult* ReportStatusRequest::mutable_results(int index) {
  // @@protoc_insertion_point(field_mutable:lars.ReportStatusRequest.results)
  return results_.Mutable(index);
}
inline ::lars::HostCallResult* ReportStatusRequest::add_results() {
  // @@protoc_insertion_point(field_add:lars.ReportStatusRequest.results)
  return results_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::lars::HostCallResult >*
ReportStatusRequest::mutable_results() {
  // @@protoc_insertion_point(field_mutable_list:lars.ReportStatusRequest.results)
  return &results_;
}
inline const ::google::protobuf::RepeatedPtrField< ::lars::HostCallResult >&
ReportStatusRequest::results() const {
  // @@protoc_insertion_point(field_list:lars.ReportStatusRequest.results)
  return results_;
}

// uint32 ts = 5;
inline void ReportStatusRequest::clear_ts() {
  ts_ = 0u;
}
inline ::google::protobuf::uint32 ReportStatusRequest::ts() const {
  // @@protoc_insertion_point(field_get:lars.ReportStatusRequest.ts)
  return ts_;
}
inline void ReportStatusRequest::set_ts(::google::protobuf::uint32 value) {
  
  ts_ = value;
  // @@protoc_insertion_point(field_set:lars.ReportStatusRequest.ts)
}

// -------------------------------------------------------------------

// GetHostRequest

// uint32 seq = 1;
inline void GetHostRequest::clear_seq() {
  seq_ = 0u;
}
inline ::google::protobuf::uint32 GetHostRequest::seq() const {
  // @@protoc_insertion_point(field_get:lars.GetHostRequest.seq)
  return seq_;
}
inline void GetHostRequest::set_seq(::google::protobuf::uint32 value) {
  
  seq_ = value;
  // @@protoc_insertion_point(field_set:lars.GetHostRequest.seq)
}

// int32 modid = 2;
inline void GetHostRequest::clear_modid() {
  modid_ = 0;
}
inline ::google::protobuf::int32 GetHostRequest::modid() const {
  // @@protoc_insertion_point(field_get:lars.GetHostRequest.modid)
  return modid_;
}
inline void GetHostRequest::set_modid(::google::protobuf::int32 value) {
  
  modid_ = value;
  // @@protoc_insertion_point(field_set:lars.GetHostRequest.modid)
}

// int32 cmdid = 3;
inline void GetHostRequest::clear_cmdid() {
  cmdid_ = 0;
}
inline ::google::protobuf::int32 GetHostRequest::cmdid() const {
  // @@protoc_insertion_point(field_get:lars.GetHostRequest.cmdid)
  return cmdid_;
}
inline void GetHostRequest::set_cmdid(::google::protobuf::int32 value) {
  
  cmdid_ = value;
  // @@protoc_insertion_point(field_set:lars.GetHostRequest.cmdid)
}

// -------------------------------------------------------------------

// GetHostResponse

// uint32 seq = 1;
inline void GetHostResponse::clear_seq() {
  seq_ = 0u;
}
inline ::google::protobuf::uint32 GetHostResponse::seq() const {
  // @@protoc_insertion_point(field_get:lars.GetHostResponse.seq)
  return seq_;
}
inline void GetHostResponse::set_seq(::google::protobuf::uint32 value) {
  
  seq_ = value;
  // @@protoc_insertion_point(field_set:lars.GetHostResponse.seq)
}

// int32 modid = 2;
inline void GetHostResponse::clear_modid() {
  modid_ = 0;
}
inline ::google::protobuf::int32 GetHostResponse::modid() const {
  // @@protoc_insertion_point(field_get:lars.GetHostResponse.modid)
  return modid_;
}
inline void GetHostResponse::set_modid(::google::protobuf::int32 value) {
  
  modid_ = value;
  // @@protoc_insertion_point(field_set:lars.GetHostResponse.modid)
}

// int32 cmdid = 3;
inline void GetHostResponse::clear_cmdid() {
  cmdid_ = 0;
}
inline ::google::protobuf::int32 GetHostResponse::cmdid() const {
  // @@protoc_insertion_point(field_get:lars.GetHostResponse.cmdid)
  return cmdid_;
}
inline void GetHostResponse::set_cmdid(::google::protobuf::int32 value) {
  
  cmdid_ = value;
  // @@protoc_insertion_point(field_set:lars.GetHostResponse.cmdid)
}

// int32 retcode = 4;
inline void GetHostResponse::clear_retcode() {
  retcode_ = 0;
}
inline ::google::protobuf::int32 GetHostResponse::retcode() const {
  // @@protoc_insertion_point(field_get:lars.GetHostResponse.retcode)
  return retcode_;
}
inline void GetHostResponse::set_retcode(::google::protobuf::int32 value) {
  
  retcode_ = value;
  // @@protoc_insertion_point(field_set:lars.GetHostResponse.retcode)
}

// .lars.HostInfo host = 5;
inline bool GetHostResponse::has_host() const {
  return this != internal_default_instance() && host_ != NULL;
}
inline void GetHostResponse::clear_host() {
  if (GetArenaNoVirtual() == NULL && host_ != NULL) delete host_;
  host_ = NULL;
}
inline const ::lars::HostInfo& GetHostResponse::host() const {
  const ::lars::HostInfo* p = host_;
  // @@protoc_insertion_point(field_get:lars.GetHostResponse.host)
  return p != NULL ? *p : *reinterpret_cast<const ::lars::HostInfo*>(
      &::lars::_HostInfo_default_instance_);
}
inline ::lars::HostInfo* GetHostResponse::mutable_host() {
  
  if (host_ == NULL) {
    host_ = new ::lars::HostInfo;
  }
  // @@protoc_insertion_point(field_mutable:lars.GetHostResponse.host)
  return host_;
}
inline ::lars::HostInfo* GetHostResponse::release_host() {
  // @@protoc_insertion_point(field_release:lars.GetHostResponse.host)
  
  ::lars::HostInfo* temp = host_;
  host_ = NULL;
  return temp;
}
inline void GetHostResponse::set_allocated_host(::lars::HostInfo* host) {
  delete host_;
  host_ = host;
  if (host) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:lars.GetHostResponse.host)
}

// -------------------------------------------------------------------

// ReportRequest

// int32 modid = 1;
inline void ReportRequest::clear_modid() {
  modid_ = 0;
}
inline ::google::protobuf::int32 ReportRequest::modid() const {
  // @@protoc_insertion_point(field_get:lars.ReportRequest.modid)
  return modid_;
}
inline void ReportRequest::set_modid(::google::protobuf::int32 value) {
  
  modid_ = value;
  // @@protoc_insertion_point(field_set:lars.ReportRequest.modid)
}

// int32 cmdid = 2;
inline void ReportRequest::clear_cmdid() {
  cmdid_ = 0;
}
inline ::google::protobuf::int32 ReportRequest::cmdid() const {
  // @@protoc_insertion_point(field_get:lars.ReportRequest.cmdid)
  return cmdid_;
}
inline void ReportRequest::set_cmdid(::google::protobuf::int32 value) {
  
  cmdid_ = value;
  // @@protoc_insertion_point(field_set:lars.ReportRequest.cmdid)
}

// .lars.HostInfo host = 3;
inline bool ReportRequest::has_host() const {
  return this != internal_default_instance() && host_ != NULL;
}
inline void ReportRequest::clear_host() {
  if (GetArenaNoVirtual() == NULL && host_ != NULL) delete host_;
  host_ = NULL;
}
inline const ::lars::HostInfo& ReportRequest::host() const {
  const ::lars::HostInfo* p = host_;
  // @@protoc_insertion_point(field_get:lars.ReportRequest.host)
  return p != NULL ? *p : *reinterpret_cast<const ::lars::HostInfo*>(
      &::lars::_HostInfo_default_instance_);
}
inline ::lars::HostInfo* ReportRequest::mutable_host() {
  
  if (host_ == NULL) {
    host_ = new ::lars::HostInfo;
  }
  // @@protoc_insertion_point(field_mutable:lars.ReportRequest.host)
  return host_;
}
inline ::lars::HostInfo* ReportRequest::release_host() {
  // @@protoc_insertion_point(field_release:lars.ReportRequest.host)
  
  ::lars::HostInfo* temp = host_;
  host_ = NULL;
  return temp;
}
inline void ReportRequest::set_allocated_host(::lars::HostInfo* host) {
  delete host_;
  host_ = host;
  if (host) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:lars.ReportRequest.host)
}

// int32 retcode = 4;
inline void ReportRequest::clear_retcode() {
  retcode_ = 0;
}
inline ::google::protobuf::int32 ReportRequest::retcode() const {
  // @@protoc_insertion_point(field_get:lars.ReportRequest.retcode)
  return retcode_;
}
inline void ReportRequest::set_retcode(::google::protobuf::int32 value) {
  
  retcode_ = value;
  // @@protoc_insertion_point(field_set:lars.ReportRequest.retcode)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace lars

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::lars::MessageId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::lars::MessageId>() {
  return ::lars::MessageId_descriptor();
}
template <> struct is_proto_enum< ::lars::LarsRetCode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::lars::LarsRetCode>() {
  return ::lars::LarsRetCode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_lars_2eproto__INCLUDED
